### ISSUE TITLE
Mobile layout is missing the Saved page on Navbar

### ISSUE THREAD

**Issue by taqft** [theresaqueryforthat/namepass#30]
![image](https://user-images.githubusercontent.com/70115233/145509441-986169a0-885b-4498-a6ea-04bf5b462c8c.png)

===

![image](https://user-images.githubusercontent.com/70115233/145509542-445c7c42-3386-42e8-aa99-b791d6d76638.png)

**Comment by taqft** [comment]
@atmention what do you think?

**Comment by atmention** [comment]
This is what I asked you about before class when I asked if the hamburger
was there when we shrunk the page

**Comment by taqft** [comment]
Fixed above
